import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F3F4F6' },

  // Header
  header: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTop: { alignItems: 'center' },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  backButton: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  logo: { height: 48, width: 160 },
  titleText: { fontSize: 20, fontWeight: '700', color: '#111827' },
  exportBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 14, paddingVertical: 8,
    borderRadius: 20,
  },
  exportBtnText: { fontSize: 13, fontWeight: '600', color: '#374151' },

  // Filters
  filtersRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 12 },
  filterBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: '#FFFFFF', borderRadius: 10,
    paddingHorizontal: 16, paddingVertical: 9,
    borderWidth: 1, borderColor: '#E5E7EB',
  },
  filterBtnActive: { backgroundColor: '#1E5BAC', borderColor: '#1E5BAC' },
  filterBtnText: { fontSize: 13, fontWeight: '600', color: '#374151' },
  filterBtnTextActive: { color: '#FFFFFF' },
  dropdown: {
    position: 'absolute', top: 44, left: 0, zIndex: 50,
    backgroundColor: '#FFFFFF', borderRadius: 12,
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12, shadowRadius: 8, elevation: 8,
    minWidth: 160, borderWidth: 1, borderColor: '#F3F4F6',
    paddingVertical: 4, maxHeight: 300,
  },
  dropdownItem: {
    flexDirection: 'row', alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14, paddingVertical: 10,
  },
  dropdownItemText: { fontSize: 13, color: '#374151' },
  dropdownItemSelected: { color: '#1E5BAC', fontWeight: '600' },
  dropdownCheck: { color: '#1E5BAC', fontWeight: '700', fontSize: 14 },

  // List
  listContent: { padding: 12, paddingBottom: 100, gap: 10 },
  loadingBox: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyBox: { alignItems: 'center', paddingVertical: 60 },
  emptyText: { fontSize: 15, color: '#9CA3AF' },
  emptyBoxLarge: { alignItems: 'center', paddingVertical: 48, gap: 12 },
  emptyIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 17,
    color: '#111827',
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 19,
    paddingHorizontal: 24,
  },
  emptyCTABtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E5BAC',
    borderRadius: 14,
    paddingHorizontal: 24,
    paddingVertical: 13,
    marginTop: 4,
    shadowColor: '#1E5BAC',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 5,
  },
  emptyCTAText: {
    fontSize: 14,
    color: '#FFFFFF',
  },

  // Expense Card
  expenseCard: {
    backgroundColor: '#FFFFFF', borderRadius: 20,
    padding: 16, flexDirection: 'row',
    alignItems: 'flex-start', justifyContent: 'space-between',
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05, shadowRadius: 3, elevation: 2,
    borderWidth: 1, borderColor: '#F3F4F6',
  },
  expenseCardLeft: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, flex: 1 },
  expenseIconBox: {
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: '#FCE7F3',
    justifyContent: 'center', alignItems: 'center', flexShrink: 0,
  },
  expenseIconText: { fontSize: 24, color: '#DB2777', fontWeight: '300', lineHeight: 28 },
  expenseDesc: { fontSize: 15, fontWeight: '600', color: '#111827', marginBottom: 4 },
  expenseMeta: { fontSize: 13, color: '#6B7280' },
  expenseAmount: { fontSize: 17, fontWeight: '700', color: '#DC2626' },
  expenseAmountBlock: { alignItems: 'flex-end', marginLeft: 10, gap: 4 },
  expenseVatText: { fontSize: 11, fontWeight: '600', color: '#6B7280' },
  expenseBadgeRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6, marginTop: 8 },
  expenseCategoryBadge: {
    maxWidth: 150,
    borderRadius: 999,
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  expenseCategoryBadgeText: { fontSize: 10, fontWeight: '700', color: '#1E5BAC' },
  expenseMiniBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  expenseMiniBadgeText: { fontSize: 10, fontWeight: '700', color: '#1E5BAC' },
  expenseOcrBadge: { backgroundColor: '#F5F3FF', borderColor: '#DDD6FE' },
  expenseOcrBadgeText: { color: '#7C3AED' },

  expenseDashboardCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: '#E8EEF8',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  expenseDashboardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  expenseDashboardEyebrow: { fontSize: 11, fontWeight: '800', color: '#64748B', textTransform: 'uppercase' },
  expenseDashboardTotal: { fontSize: 28, fontWeight: '800', color: '#0F172A', marginTop: 4 },
  expenseDashboardTrend: { fontSize: 12, fontWeight: '700', color: '#1E5BAC', marginTop: 4 },
  expenseDashboardIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  expenseMetricGrid: { flexDirection: 'row', gap: 8 },
  expenseMetricTile: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    padding: 10,
    minHeight: 70,
  },
  expenseMetricLabel: { fontSize: 10, fontWeight: '700', color: '#64748B', marginBottom: 4 },
  expenseMetricValue: { fontSize: 14, fontWeight: '800', color: '#111827' },
  expenseMetricHint: { fontSize: 10, color: '#64748B', marginTop: 3 },

  expenseQuickActions: { flexDirection: 'row', gap: 8 },
  expenseQuickAction: {
    flex: 1,
    minHeight: 76,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EEF8',
    padding: 10,
    justifyContent: 'space-between',
  },
  expenseQuickActionIcon: {
    width: 30,
    height: 30,
    borderRadius: 12,
    backgroundColor: '#EFF6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  expenseQuickActionText: { fontSize: 11, fontWeight: '800', color: '#111827', lineHeight: 14 },

  expenseSectionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: '#F0F4FA',
  },
  expenseSectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  expenseSectionTitle: { fontSize: 15, fontWeight: '800', color: '#111827' },
  expenseSectionSub: { fontSize: 11, fontWeight: '600', color: '#64748B' },
  categoryBreakdownRow: { gap: 8 },
  categoryBreakdownItem: {
    borderRadius: 14,
    padding: 10,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#EEF2F7',
  },
  categoryBreakdownItemActive: { backgroundColor: '#EFF6FF', borderColor: '#93C5FD' },
  categoryBreakdownTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 10 },
  categoryBreakdownName: { flex: 1, fontSize: 12, fontWeight: '800', color: '#111827' },
  categoryBreakdownAmount: { fontSize: 12, fontWeight: '800', color: '#1E5BAC' },
  categoryBreakdownTrack: {
    height: 7,
    borderRadius: 99,
    overflow: 'hidden',
    backgroundColor: '#E5EAF2',
    marginTop: 8,
  },
  categoryBreakdownFill: { height: 7, borderRadius: 99, backgroundColor: '#1E5BAC' },
  categoryBreakdownMeta: { fontSize: 10, fontWeight: '700', color: '#64748B', marginTop: 6 },

  smartFilterScroll: { marginHorizontal: -14 },
  smartFilterContent: { paddingHorizontal: 14, gap: 8 },
  smartFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5EAF2',
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  smartFilterChipActive: { backgroundColor: '#1E5BAC', borderColor: '#1E5BAC' },
  smartFilterChipText: { fontSize: 12, fontWeight: '700', color: '#334155' },
  smartFilterChipTextActive: { color: '#FFFFFF' },

  insightCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5EAF2',
    padding: 10,
  },
  insightIcon: {
    width: 30,
    height: 30,
    borderRadius: 12,
    backgroundColor: '#ECFDF5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  insightText: { flex: 1, fontSize: 12, fontWeight: '700', color: '#334155', lineHeight: 17 },

  expenseSmartAlertsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: '#E8EEF8',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  smartAlertList: { gap: 8 },
  smartAlertItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5EAF2',
    borderLeftWidth: 3,
    padding: 10,
  },
  smartAlertIcon: {
    width: 32,
    height: 32,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  smartAlertBody: { flex: 1, minWidth: 0 },
  smartAlertTitle: { fontSize: 12, fontWeight: '800', color: '#111827' },
  smartAlertDescription: { fontSize: 11, fontWeight: '600', color: '#64748B', lineHeight: 15, marginTop: 2 },
  smartAlertCta: { fontSize: 11, fontWeight: '800', marginTop: 5 },
  smartAlertDismiss: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  expenseSmartInsightsStrip: {
    marginHorizontal: -4,
  },
  smartInsightContent: { paddingHorizontal: 4, gap: 8 },
  smartInsightPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: 230,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8EEF8',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  smartInsightText: { fontSize: 11, fontWeight: '700', color: '#334155' },

  // Expense Alert Card
  expenseAlertCard: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: '#FFFBEB', borderRadius: 20, padding: 16,
    borderWidth: 1, borderColor: '#FDE68A',
  },
  expenseAlertLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  expenseAlertIcon: {
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: '#F59E0B',
    justifyContent: 'center', alignItems: 'center', flexShrink: 0,
  },
  expenseAlertText: { fontSize: 14, fontWeight: '600', color: '#111827', flex: 1, marginRight: 12 },
  expenseAlertBtn: {
    backgroundColor: '#1E5BAC', borderRadius: 20,
    paddingHorizontal: 14, paddingVertical: 9,
  },
  expenseAlertBtnText: { fontSize: 13, fontWeight: '600', color: '#FFFFFF' },

  // FAB
  fab: {
    position: 'absolute', bottom: 28, right: 20,
    width: 56, height: 56, borderRadius: 28,
    backgroundColor: '#1E5BAC',
    justifyContent: 'center', alignItems: 'center',
    shadowColor: '#1E5BAC', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35, shadowRadius: 8, elevation: 8,
  },

  // Modal shared
  modalContainer: { flex: 1, backgroundColor: '#F5F7FF' },
  modalHeader: {
    flexDirection: 'row', alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16, paddingVertical: 14,
    backgroundColor: '#F5F7FF',
    borderBottomWidth: 1, borderBottomColor: '#E5E7EB',
  },
  modalCancelText: { fontSize: 15, fontWeight: '500', color: '#1E5BAC' },
  modalTitle: { fontSize: 15, fontWeight: '600', color: '#1F2937', flex: 1, textAlign: 'center', marginHorizontal: 8 },
  modalConfirmBtn: {
    backgroundColor: '#1E5BAC', borderRadius: 8,
    paddingHorizontal: 14, paddingVertical: 8,
    minWidth: 80, alignItems: 'center',
  },
  modalConfirmText: { fontSize: 13, fontWeight: '600', color: '#FFFFFF' },
  modalContent: { padding: 16, paddingBottom: 40 },

  // Form card
  formCard: {
    backgroundColor: '#FFFFFF', borderRadius: 16,
    padding: 18, gap: 16,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05, shadowRadius: 3, elevation: 2,
  },
  uploadArea: { flexDirection: 'row', gap: 12 },
  uploadBtn: {
    flex: 1, flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
    gap: 6, backgroundColor: '#F9FAFB',
    borderWidth: 1, borderColor: '#E0E7FF', borderRadius: 12,
    paddingVertical: 14, paddingHorizontal: 8,
  },
  uploadBtnText: { fontSize: 11, fontWeight: '500', color: '#374151', textAlign: 'center', flexShrink: 1 },

  // Attachment preview card
  attachmentPreview: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#F0F4FF', borderRadius: 12,
    borderWidth: 1, borderColor: '#C7D2FE',
    padding: 10, gap: 10,
  },
  attachmentThumbWrapper: {
    width: 56, height: 56, borderRadius: 8,
    overflow: 'hidden', flexShrink: 0,
  },
  attachmentThumb: { width: 56, height: 56 },
  attachmentThumbOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.28)',
    justifyContent: 'center', alignItems: 'center',
  },
  attachmentFileIconBox: {
    width: 56, height: 56, borderRadius: 8,
    backgroundColor: '#E0E7FF',
    justifyContent: 'center', alignItems: 'center', flexShrink: 0,
  },
  attachmentInfo: { flex: 1 },
  attachmentFileName: { fontSize: 13, fontWeight: '600', color: '#1F2937' },
  attachmentFileMeta: { fontSize: 11, color: '#6B7280', marginTop: 2 },
  attachmentRemoveBtn: {
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center', alignItems: 'center', flexShrink: 0,
  },

  // Full-screen image preview
  imagePreviewOverlay: {
    flex: 1, backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center', alignItems: 'center',
  },
  imagePreviewClose: {
    position: 'absolute', top: 56, right: 20,
    width: 40, height: 40, borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.18)',
    justifyContent: 'center', alignItems: 'center',
    zIndex: 10,
  },
  imagePreviewFull: { width: '100%', height: '80%' },

  fieldBlock: { gap: 6 },
  fieldLabelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  fieldLabel: { fontSize: 13, fontWeight: '600', color: '#374151' },
  required: { color: '#1E5BAC' },
  optional: { fontSize: 12, fontWeight: '400', color: '#9CA3AF' },
  fieldInput: {
    backgroundColor: '#F3F4F6', borderRadius: 10,
    borderWidth: 1, borderColor: '#E5E7EB',
    paddingHorizontal: 14, paddingVertical: 12,
    fontSize: 14, color: '#1F2937',
  },
  fieldInputRow: { flexDirection: 'row', alignItems: 'center' },
  fieldUnit: { fontSize: 13, fontWeight: '500', color: '#6B7280', marginLeft: 8 },
  pickerRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: '#F3F4F6', borderRadius: 10,
    borderWidth: 1, borderColor: '#E5E7EB',
    paddingHorizontal: 14, paddingVertical: 13,
  },
  pickerPlaceholderText: { fontSize: 14, color: '#9CA3AF', flex: 1 },
  pickerValueText: { fontSize: 14, color: '#1F2937', flex: 1, fontWeight: '500' },
  totalsBlock: { borderTopWidth: 1, borderTopColor: '#F3F4F6', paddingTop: 12, gap: 8 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  totalRowLast: { paddingTop: 8, borderTopWidth: 1, borderTopColor: '#F3F4F6' },
  totalLabel: { fontSize: 14, color: '#6B7280', fontWeight: '500' },
  totalValue: { fontSize: 14, color: '#374151', fontWeight: '500' },
  totalLabelBold: { fontSize: 15, fontWeight: '700', color: '#1F2937' },
  totalValueBold: { fontSize: 15, fontWeight: '700', color: '#1E5BAC' },
  confirmBtn: {
    backgroundColor: '#1E5BAC', borderRadius: 12,
    paddingVertical: 14, alignItems: 'center',
    shadowColor: '#1E5BAC', shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25, shadowRadius: 6, elevation: 4,
  },
  confirmBtnText: { fontSize: 15, fontWeight: '700', color: '#FFFFFF' },

  // Pickers
  pickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  pickerSheet: {
    backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20,
    paddingVertical: 12, paddingHorizontal: 8, maxHeight: 400,
  },
  pickerSheetTitle: {
    fontSize: 14, fontWeight: '700', color: '#374151',
    paddingHorizontal: 12, paddingBottom: 8, marginBottom: 4,
    borderBottomWidth: 1, borderBottomColor: '#F3F4F6',
  },
  pickerSheetTitleRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 12, paddingBottom: 8, marginBottom: 4,
    borderBottomWidth: 1, borderBottomColor: '#F3F4F6',
  },
  pickerSheetTitleText: { fontSize: 14, fontWeight: '700', color: '#374151' },
  pickerSheetAddBtn: {
    width: 30, height: 30, borderRadius: 15,
    backgroundColor: '#EEF2FF',
    justifyContent: 'center', alignItems: 'center',
  },
  pickerOption: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 14, paddingVertical: 13,
    borderBottomWidth: 1, borderBottomColor: '#F9FAFB',
  },
  pickerOptionText: { fontSize: 14, color: '#374151' },
  pickerOptionSelected: { color: '#1E5BAC', fontWeight: '600' },
  pickerCheck: { fontSize: 15, color: '#1E5BAC', fontWeight: '700' },

  // Detail Modal
  detailModalHeader: {
    flexDirection: 'row', alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: '#F3F4F6',
    backgroundColor: '#FFFFFF',
  },
  detailModalTitle: { fontSize: 16, fontWeight: '600', color: '#1F2937' },
  detailCloseBtn: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center', alignItems: 'center',
  },
  detailHero: { alignItems: 'center', gap: 6, paddingVertical: 8 },
  badgeRedLg: { backgroundColor: '#FEE2E2', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 4 },
  badgeRedLgText: { fontSize: 12, fontWeight: '600', color: '#DC2626' },
  detailAmount: { fontSize: 28, fontWeight: '700', color: '#DC2626' },
  detailDate: { fontSize: 13, color: '#9CA3AF' },
  detailCard: {
    backgroundColor: '#FFFFFF', borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05, shadowRadius: 3, elevation: 2,
  },
  detailRow: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', paddingHorizontal: 16, paddingVertical: 13,
    borderBottomWidth: 1, borderBottomColor: '#F9FAFB',
  },
  detailRowLabel: { fontSize: 14, color: '#6B7280', flexShrink: 1 },
  detailRowValue: { fontSize: 14, fontWeight: '600', color: '#1F2937', flexShrink: 1, textAlign: 'right' },
  statusCompleted: { color: '#16A34A' },
  statusPending: { color: '#EA580C' },
  attachmentCard: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: '#EFF6FF', borderRadius: 12, padding: 14,
    borderWidth: 1, borderColor: '#BFDBFE',
  },
  attachmentLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  attachmentIconBox: {
    width: 40, height: 40, borderRadius: 8,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center', alignItems: 'center',
  },
  attachmentName: { fontSize: 13, fontWeight: '600', color: '#1E3A5F' },
  attachmentSub: { fontSize: 11, color: '#3B82F6', marginTop: 2 },
  attachmentDownload: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  noAttachment: {
    borderWidth: 2, borderStyle: 'dashed', borderColor: '#E5E7EB',
    borderRadius: 12, padding: 24, alignItems: 'center', gap: 6,
  },
  noAttachmentText: { fontSize: 13, color: '#9CA3AF' },
  noAttachmentLink: { fontSize: 13, fontWeight: '600', color: '#1E5BAC' },
  detailFooter: {
    flexDirection: 'row', gap: 12,
    padding: 16, borderTopWidth: 1, borderTopColor: '#F3F4F6',
    backgroundColor: '#F9FAFB',
  },
  detailDeleteBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 8, paddingVertical: 13, borderRadius: 12, backgroundColor: '#FEF2F2',
  },
  detailDeleteText: { fontSize: 14, fontWeight: '600', color: '#DC2626' },
  detailEditBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 8, paddingVertical: 13, borderRadius: 12, backgroundColor: '#1E5BAC',
  },
  detailEditText: { fontSize: 14, fontWeight: '600', color: '#FFFFFF' },

  // Redesigned detail modal styles
  detailHeaderBack: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  detailHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  detailHeaderBtn: {
    width: 36, height: 36, borderRadius: 10,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center', alignItems: 'center',
  },
  detailHeaderBtnDanger: { backgroundColor: '#FEE2E2' },
  detailHeaderBtnPrimary: { backgroundColor: '#EFF6FF' },

  detailAmountSection: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    backgroundColor: '#FFFFFF', borderRadius: 16, padding: 16,
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05, shadowRadius: 3, elevation: 2,
  },
  detailExpenseIconCircle: {
    width: 52, height: 52, borderRadius: 26,
    backgroundColor: '#FCE7F3',
    justifyContent: 'center', alignItems: 'center',
  },
  detailExpenseCategoryName: { fontSize: 16, fontWeight: '700', color: '#1F2937' },

  detailSectionTitle: {
    fontSize: 14, fontWeight: '700', color: '#374151', marginBottom: -4,
  },

  detailRowLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  detailRowIconBox: {
    width: 36, height: 36, borderRadius: 10,
    justifyContent: 'center', alignItems: 'center',
  },
  detailRowRight: { flexShrink: 1, flexDirection: 'row', alignItems: 'center', gap: 6, maxWidth: '50%' },

  detailAttachSection: {
    backgroundColor: '#FFFFFF', borderRadius: 16, overflow: 'hidden',
    shadowColor: '#000', shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05, shadowRadius: 3, elevation: 2,
    padding: 16, gap: 12,
  },
  detailAttachHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  detailAttachTitle: { fontSize: 14, fontWeight: '700', color: '#374151' },

  attachAddBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 10, paddingVertical: 13, borderRadius: 12,
    borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#BFDBFE',
    backgroundColor: '#EFF6FF',
  },
  attachAddIcon: {
    width: 24, height: 24, borderRadius: 12,
    backgroundColor: '#3B82F6',
    justifyContent: 'center', alignItems: 'center',
  },
  attachAddText: { fontSize: 14, fontWeight: '600', color: '#1E5BAC' },

  // Date Picker bottom sheet
  datePickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  datePickerSheet: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingBottom: 16,
    overflow: 'hidden',
  },
  datePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  datePickerTitle: { fontSize: 15, fontWeight: '700', color: '#1F2937' },
  datePickerCancel: { fontSize: 15, fontWeight: '500', color: '#6B7280' },
  datePickerOk: { fontSize: 15, fontWeight: '700', color: '#1E5BAC' },

  // Validation error
  fieldError: {
    fontSize: 12,
    color: '#DC2626',
    marginTop: 3,
    fontWeight: '500',
  },
  fieldInputError: {
    borderColor: '#DC2626',
    backgroundColor: '#FFF5F5',
  },

  // Disabled confirm buttons
  modalConfirmBtnDisabled: {
    backgroundColor: '#93C5FD',
  },
  confirmBtnDisabled: {
    backgroundColor: '#93C5FD',
    shadowOpacity: 0,
    elevation: 0,
  },

  // Supplier search inside picker
  pickerSheetAddBtnActive: {
    backgroundColor: '#1E5BAC',
  },
  supplierSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginHorizontal: 8,
    marginBottom: 8,
  },
  supplierSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1F2937',
    paddingVertical: 0,
  },

  // Pie chart
  pieCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  pieTitle: { fontSize: 15, fontWeight: '700', color: '#1F2937', marginBottom: 16 },
  pieLoader: { height: 180, justifyContent: 'center', alignItems: 'center' },
  pieEmpty: { height: 100, justifyContent: 'center', alignItems: 'center' },
  pieEmptyText: { fontSize: 13, color: '#9CA3AF' },
  pieChartRow: { alignItems: 'center', marginBottom: 20 },
  pieCenterValue: { fontSize: 16, fontWeight: '700', color: '#1F2937', textAlign: 'center' },
  pieCenterLabel: { fontSize: 11, color: '#6B7280', textAlign: 'center' },
  pieLegend: { gap: 10 },
  pieLegendRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  pieLegendDot: { width: 10, height: 10, borderRadius: 5, flexShrink: 0 },
  pieLegendLabel: { flex: 1, fontSize: 13, color: '#374151' },
  pieLegendPct: { fontSize: 13, fontWeight: '600', color: '#1F2937' },

  ocrLoadingCard: {
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    padding: 20,
    alignItems: 'center' as const,
    overflow: 'hidden' as const,
    shadowColor: '#1E5BAC',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  ocrIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#DBEAFE',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginBottom: 12,
  },
  ocrScanTrack: {
    width: '100%' as any,
    height: 3,
    backgroundColor: '#BFDBFE',
    borderRadius: 2,
    overflow: 'hidden' as const,
    marginBottom: 14,
  },
  ocrScanBeam: {
    width: 80,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#1E5BAC',
  },
  ocrTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: '#1E3A5F',
    marginBottom: 4,
    textAlign: 'center' as const,
  },
  ocrSubtitle: {
    fontSize: 12,
    color: '#3B82F6',
    textAlign: 'center' as const,
    fontWeight: '500' as const,
  },
  ocrSuccessCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    borderRadius: 14,
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    padding: 12,
  },
  ocrSuccessIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#16A34A',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  ocrSuccessTitle: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: '#166534',
  },
  ocrSuccessSubtitle: {
    fontSize: 12,
    color: '#3F6212',
    marginTop: 2,
    lineHeight: 16,
  },
  ocrReviewCard: {
    padding: 12,
    marginBottom: 12,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5EAF2',
  },
  ocrReviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  ocrReviewTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  ocrReviewTitle: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: '#111827',
  },
  ocrConfidenceBadge: {
    borderRadius: 99,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: '#EEF2FF',
  },
  ocrConfidenceHigh: {
    backgroundColor: '#DCFCE7',
  },
  ocrConfidenceMedium: {
    backgroundColor: '#FEF3C7',
  },
  ocrConfidenceLow: {
    backgroundColor: '#FEE2E2',
  },
  ocrConfidenceText: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: '#1E5BAC',
  },
  ocrConfidenceTextHigh: {
    color: '#15803D',
  },
  ocrConfidenceTextMedium: {
    color: '#B45309',
  },
  ocrConfidenceTextLow: {
    color: '#B91C1C',
  },
  ocrReviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  ocrReviewPill: {
    minWidth: '30%' as any,
    flexGrow: 1,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  ocrReviewPillLabel: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: '#6B7280',
    marginBottom: 2,
  },
  ocrReviewPillValue: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: '#111827',
  },
  ocrReviewDangerText: {
    color: '#DC2626',
    fontSize: 12,
    marginBottom: 8,
    lineHeight: 17,
  },
  ocrReviewWarnings: {
    marginBottom: 8,
  },
  ocrReviewWarningText: {
    color: '#92400E',
    fontSize: 12,
    lineHeight: 17,
  },
  ocrApplyButton: {
    backgroundColor: '#1E5BAC',
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: 'center',
  },
  ocrApplyButtonText: {
    color: '#FFFFFF',
    fontWeight: '700' as const,
  },
});
